<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GameSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $games = [
                [
                    'title' => 'New Super Mario Bros',
                    'imageUrl' => 'https://www.nintendo.com/eu/media/images/10_share_images/games_15/nintendo_ds_22/SI_NDS_NewSuperMarioBrosDS_image1600w.jpg',
                    'plateform' => 'Wii',
                    'sort' => 'Platform game',
                    'developper' => 'Nintendo',
                    'releaseDate' => '2006-05-15',
                    'inventory' => 8,
                ],
                [
                    'title' => 'The Legend of Zelda: Breath of the Wild',
                    'imageUrl' => 'https://www.zelda.com/breath-of-the-wild/assets/media/header/Main-Day.jpg',
                    'plateform' => 'Nintendo Switch',
                    'sort' => 'Action-adventure',
                    'developper' => 'Nintendo',
                    'releaseDate' => '2017-03-03',
                    'inventory' => 5,
                ],
                [
                    'title' => 'God of War Ragnarök',
                    'imageUrl' => 'https://image.api.playstation.com/vulcan/ap/rnd/202109/3016/RQfPHC1d9ZZu3cC73BQjUvzH.png',
                    'plateform' => 'PlayStation 5',
                    'sort' => 'Action-adventure',
                    'developper' => 'Santa Monica Studio',
                    'releaseDate' => '2022-11-09',
                    'inventory' => 3,
                ],
                [
                    'title' => 'Halo Infinite',
                    'imageUrl' => 'https://cdn.cloudflare.steamstatic.com/steam/apps/1240440/header.jpg',
                    'plateform' => 'Xbox Series X',
                    'sort' => 'First-person shooter',
                    'developper' => '343 Industries',
                    'releaseDate' => '2021-12-08',
                    'inventory' => 7,
                ],
                [
                    'title' => 'Minecraft',
                    'imageUrl' => 'https://upload.wikimedia.org/wikipedia/en/5/51/Minecraft_cover.png',
                    'plateform' => 'PC',
                    'sort' => 'Sandbox / Survival',
                    'developper' => 'Mojang Studios',
                    'releaseDate' => '2011-11-18',
                    'inventory' => 12,
                ],
                [
                    'title' => 'Red Dead Redemption 2',
                    'imageUrl' => 'https://cdn1.epicgames.com/offer/9e115e6f188845129e3a33c809b2f4b9/EGS_RedDeadRedemption2_RockstarGames_S2_1200x1600-20661f657871c5e71b2e6fdd16fc019e',
                    'plateform' => 'PlayStation 4',
                    'sort' => 'Action-adventure / Open World',
                    'developper' => 'Rockstar Games',
                    'releaseDate' => '2018-10-26',
                    'inventory' => 4,
                ],
                [
                    'title' => 'Animal Crossing: New Horizons',
                    'imageUrl' => 'https://www.nintendo.com/eu/media/images/10_share_images/games_15/nintendo_switch_8/SI_NSwitch_AnimalCrossingNewHorizons_image1600w.jpg',
                    'plateform' => 'Nintendo Switch',
                    'sort' => 'Simulation',
                    'developper' => 'Nintendo',
                    'releaseDate' => '2020-03-20',
                    'inventory' => 9,
                ],
                [
                    'title' => 'The Witcher 3: Wild Hunt',
                    'imageUrl' => 'https://cdn.akamai.steamstatic.com/steam/apps/292030/header.jpg',
                    'plateform' => 'PC',
                    'sort' => 'RPG',
                    'developper' => 'CD Projekt Red',
                    'releaseDate' => '2015-05-19',
                    'inventory' => 6,
                ],
                [
                    'title' => 'Super Smash Bros. Ultimate',
                    'imageUrl' => 'https://cdn.akamai.steamstatic.com/steam/apps/1755830/header.jpg',
                    'plateform' => 'Nintendo Switch',
                    'sort' => 'Fighting',
                    'developper' => 'Nintendo',
                    'releaseDate' => '2018-12-07',
                    'inventory' => 10,
                ],
                [
                    'title' => 'Grand Theft Auto V',
                    'imageUrl' => 'https://upload.wikimedia.org/wikipedia/en/a/a5/Grand_Theft_Auto_V.png',
                    'plateform' => 'PlayStation 4',
                    'sort' => 'Action / Open World',
                    'developper' => 'Rockstar Games',
                    'releaseDate' => '2013-09-17',
                    'inventory' => 5,
                ],
                [
                    'title' => 'Fortnite',
                    'imageUrl' => 'https://upload.wikimedia.org/wikipedia/en/thumb/0/09/Fortnite_%282017_video_game%29.jpg/220px-Fortnite_%282017_video_game%29.jpg',
                    'plateform' => 'PC',
                    'sort' => 'Battle Royale',
                    'developper' => 'Epic Games',
                    'releaseDate' => '2017-07-21',
                    'inventory' => 15,
                ],
                [
                    'title' => 'Call of Duty: Modern Warfare II',
                    'imageUrl' => 'https://upload.wikimedia.org/wikipedia/en/f/f0/Call_of_Duty_Modern_Warfare_II_Key_Art.jpg',
                    'plateform' => 'Xbox Series X',
                    'sort' => 'First-person shooter',
                    'developper' => 'Infinity Ward',
                    'releaseDate' => '2022-10-28',
                    'inventory' => 6,
                ],
                [
                    'title' => 'Elden Ring',
                    'imageUrl' => 'https://upload.wikimedia.org/wikipedia/en/b/b9/Elden_Ring_Box_art.jpg',
                    'plateform' => 'PC',
                    'sort' => 'Action RPG',
                    'developper' => 'FromSoftware',
                    'releaseDate' => '2022-02-25',
                    'inventory' => 8,
                ],
                [
                    'title' => 'FIFA 23',
                    'imageUrl' => 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2a/FIFA_23_Cover.jpg/220px-FIFA_23_Cover.jpg',
                    'plateform' => 'PlayStation 5',
                    'sort' => 'Sports',
                    'developper' => 'EA Sports',
                    'releaseDate' => '2022-09-30',
                    'inventory' => 14,
                ],
                [
                    'title' => 'Pokémon Scarlet',
                    'imageUrl' => 'https://upload.wikimedia.org/wikipedia/en/b/b2/Pokemon_Scarlet_and_Violet_box_art.jpg',
                    'plateform' => 'Nintendo Switch',
                    'sort' => 'RPG',
                    'developper' => 'Game Freak',
                    'releaseDate' => '2022-11-18',
                    'inventory' => 9,
                ],
                [
                    'title' => 'Cyberpunk 2077',
                    'imageUrl' => 'https://cdn.akamai.steamstatic.com/steam/apps/1091500/header.jpg',
                    'plateform' => 'PC',
                    'sort' => 'RPG / Open World',
                    'developper' => 'CD Projekt Red',
                    'releaseDate' => '2020-12-10',
                    'inventory' => 4,
                ],
                [
                    'title' => 'Among Us',
                    'imageUrl' => 'https://upload.wikimedia.org/wikipedia/en/f/f3/Among_Us_cover_art.jpg',
                    'plateform' => 'PC',
                    'sort' => 'Party / Social deduction',
                    'developper' => 'Innersloth',
                    'releaseDate' => '2018-06-15',
                    'inventory' => 20,
                ],
                [
                    'title' => 'Celeste',
                    'imageUrl' => 'https://upload.wikimedia.org/wikipedia/en/9/9c/Celeste_boxart.jpg',
                    'plateform' => 'Nintendo Switch',
                    'sort' => 'Platformer',
                    'developper' => 'Matt Makes Games',
                    'releaseDate' => '2018-01-25',
                    'inventory' => 3,
                ],
                [
                    'title' => 'Stardew Valley',
                    'imageUrl' => 'https://upload.wikimedia.org/wikipedia/en/1/18/Stardew_Valley_Cover_Art.png',
                    'plateform' => 'PC',
                    'sort' => 'Simulation / Farming',
                    'developper' => 'ConcernedApe',
                    'releaseDate' => '2016-02-26',
                    'inventory' => 11,
                ],
                [
                    'title' => 'Hollow Knight',
                    'imageUrl' => 'https://upload.wikimedia.org/wikipedia/en/0/05/Hollow_Knight_cover.jpg',
                    'plateform' => 'PC',
                    'sort' => 'Metroidvania',
                    'developper' => 'Team Cherry',
                    'releaseDate' => '2017-02-24',
                    'inventory' => 7,
                ],
                [
                    'title' => 'Tetris Effect',
                    'imageUrl' => 'https://upload.wikimedia.org/wikipedia/en/7/7d/Tetris_Effect_cover.jpg',
                    'plateform' => 'PlayStation 4',
                    'sort' => 'Puzzle',
                    'developper' => 'Monstars Inc.',
                    'releaseDate' => '2018-11-09',
                    'inventory' => 6,
                ],
                [
                    'title' => 'Cuphead',
                    'imageUrl' => 'https://upload.wikimedia.org/wikipedia/en/9/9f/Cuphead_%28artwork%29.jpg',
                    'plateform' => 'Xbox One',
                    'sort' => 'Run and gun / Platformer',
                    'developper' => 'Studio MDHR',
                    'releaseDate' => '2017-09-29',
                    'inventory' => 5,
                ],
                [
                    'title' => 'Overwatch 2',
                    'imageUrl' => 'https://upload.wikimedia.org/wikipedia/en/b/b3/Overwatch_2_cover_art.jpg',
                    'plateform' => 'PC',
                    'sort' => 'First-person shooter',
                    'developper' => 'Blizzard Entertainment',
                    'releaseDate' => '2022-10-04',
                    'inventory' => 10,
                ],
                [
                    'title' => 'Persona 5 Royal',
                    'imageUrl' => 'https://upload.wikimedia.org/wikipedia/en/9/90/Persona_5_cover_art.jpg',
                    'plateform' => 'PlayStation 4',
                    'sort' => 'JRPG',
                    'developper' => 'Atlus',
                    'releaseDate' => '2019-10-31',
                    'inventory' => 6,
                ],
                [
                    'title' => 'Monster Hunter Rise',
                    'imageUrl' => 'https://upload.wikimedia.org/wikipedia/en/4/45/Monster_Hunter_Rise_cover_art.jpg',
                    'plateform' => 'Nintendo Switch',
                    'sort' => 'Action RPG',
                    'developper' => 'Capcom',
                    'releaseDate' => '2021-03-26',
                    'inventory' => 9,
                ],
            
        ];

        DB::table('games')->insert($games);
    }
}
